name: 'ECA Config'
type: module
description: 'Config events.'
core_version_requirement: ^10.3 || ^11
package: ECA
dependencies:
  - eca:eca

# Information added by Drupal.org packaging script on 2024-10-26
version: '2.0.7'
project: 'eca'
datestamp: 1729943931
