################
# GitLabCI template for Drupal projects.
#
# The full documentation is on https://project.pages.drupalcode.org/gitlab_templates/
################

# For information on alternative values for 'ref' see https://project.pages.drupalcode.org/gitlab_templates/info/templates-version/
include:
  - project: $_GITLAB_TEMPLATES_REPO
    ref: $_GITLAB_TEMPLATES_REF
    file:
      - "/includes/include.drupalci.main.yml"
      - "/includes/include.drupalci.variables.yml"
      - "/includes/include.drupalci.workflows.yml"

################
# Pipeline configuration variables are defined with default values and descriptions in the file
# https://git.drupalcode.org/project/gitlab_templates/-/blob/main/includes/include.drupalci.variables.yml
################
variables:
  _CSPELL_WORDS: "collapsiblock,testhtmlblock"
# These are only to be used to confirm compatibility when all else is passing,
# do not merge an MR with these uncommented:
#   OPT_IN_TEST_NEXT_MINOR: '1'
#   OPT_IN_TEST_NEXT_MAJOR: '1'
