include:
  - project: $_GITLAB_TEMPLATES_REPO
    ref: $_GITLAB_TEMPLATES_REF
    file:
      - '/includes/include.drupalci.main.yml'
      - '/includes/include.drupalci.variables.yml'
      - '/includes/include.drupalci.workflows.yml'

variables:
  _TARGET_DRUPAL: 10.3
  _TARGET_PHP: 8.2
  _PHPUNIT_EXTRA: --verbose
  OPT_IN_TEST_PREVIOUS_MAJOR: 0
  OPT_IN_TEST_PREVIOUS_MINOR: 0
  OPT_IN_TEST_NEXT_MINOR: 1
  OPT_IN_TEST_NEXT_MAJOR: 1
  OPT_IN_TEST_MAX_PHP: 1
  _PHPUNIT_CONCURRENT: 1
  SKIP_ESLINT: 1
  _CSPELL_WORDS: 'mixtral, bedrockruntime, ubinary, milvusv, Auphonics, tunlp, mkdocs, hmmmpf, hotswap, Gufw, Elevenlabs, elevenlabs, dropai, Drupals, dport, Deepgram, deepgram, Deepgrams, camelcase, Auphonic, auphonic, grumphp, modr, programmatical, gray, email, grey, etcdctl, erging, e-mail, echoai, Eblank, boxcolor, chatcmpl, dango, absmiddle, AICK, aickeditor, anns, AIUI, Aiui, aiui, analyse, APPROOT, approot, autocompleting, Automators, automators, autopopulated, autoresize, bangbang, BASEHOST, bento, boxolor, bullettrain, busstop, chatbots, chatmpl, Chunker, chunker, couplekiss, Dall, dall, dalle, databucket, Datasource, datasource, davinci, derivite, detab, drawtext, dsts, e-mail, eachother, endhours, endverbatim, Explainability, Falconsai, faqfield, ffprobe, Finegrained, flac, fleur, fuelpump, grey, guardswoman, Handlex, hankey, healthcheck, heartpulse, hocho, hotsprings, hyperparameters, ibilities, icecream, Initialise, interrobang, intrensic, Iskariot, izakaya, keycap, koko, laidback, libx, livechat, logprobs, Longstockings, midword, milvusdb, minidisc, MINIO, minio, minioadmin, MOCKOON, mockoon, moderations, moyai, nostdin, octect, octocat, oden, oneshot, overriden, paranthesis, Pippi, placesholders, precode, precodenum, prenum, Preprompt, preprompt, pseudofield, qscale, qslw, Radisson, Recogniztion, Renederer, Rulehelpers, scikit, seccomp,  specifices, starthours, Sublists, sublists, Summarisation, Summarise, summarise, tada, tanabata, TCHA, testsetestt, Tiktoken, tophat, unflatten, unhash, usabled, Valiudate, vals, vectordb, vframes, vsync, wantm, Webform, WHATWG, whiteline, womens, XFALSE, XTRUE, Yethee, Zilliz, zilliz, zillizcloud'
  # showdown.js is full of emoji words.
  _CSPELL_IGNORE_PATHS: 'modules/ai_chatbot/js'

cspell:
  allow_failure: false
stylelint:
  allow_failure: false
phpcs:
  allow_failure: false
phpstan:
  allow_failure: false
