social_auth_amazon.settings:
  type: config_object
  label: 'Social Auth Amazon settings'
  mapping:
    client_id:
      type: string
      label: 'Client Id'
    client_secret:
      type: string
      label: 'Client Secret'
    scopes:
      type: string
      label: 'Scopes to be requested'
    endpoints:
      type: string
      label: 'API Endpoints to be requested'
